apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nxw29n17g-nodejs
  janus-idp.io/tekton: nxw29n17g-nodejs
  backstage.io/kubernetes-id: nxw29n17g-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nxw29n17g-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
